"""
Django settings for cloudApp project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6h#=i3&0ze)7m46(*0u^$j@4$fs0q-kgh@(6v_@0i#_x+g8mq0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "store.apps.StoreConfig",
    "users.apps.UsersConfig",
    "storages"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cloudApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cloudApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = "store-home"
# LOGOUT_REDIRECT_URL = "store-home"


MEDIA_ROOT = os.path.join(BASE_DIR, "mediaFiles")
MEDIA_URL = "https://cc-a1.s3.amazonaws.com/mediaFiles/"

# # s3 bucket settings
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'

# AWS_ACCESS_KEY_ID = "ASIAZTL4CKEJ76ZIZDS5"
# AWS_S3_SESSION_PROFILE = ""
# AWS_SECRET_ACCESS_KEY = "qhPeopdnHcOBJzprOmm3/VPhE3SYD8xk+MmMnMEn"

# AWS_SESSION_TOKEN = "FwoGZXIvYXdzECUaDO7nCficA82hijKG6yLNATba/M8H73fJn2kp9/MiOFzNJGUulDQKr9nyqnKSnvxS9dHZe6GoeO8W6WDVdXT3P0jYRl6bkUMdcPRdC4gSjyPGDTxoN3Zi05HaBCX6myzNMuWFSlr9Wx+OZZTHyxs7DQMqfVPpFFc6Jwofk6vb+jHvV9jrYn9qNRus/JYD33iScW8BPmRJAeo9Ov1UZ0PHi+BdnRarrO6hQgKbNVvcNWo+QRI75iyBFimjPcEqWnykFW3ixouzdjXxdw1Fe8frNBKN5u7ckXZryAIiZMAoyfvvkgYyLVAjJH9A0WYrhZMiF/brLfRUI+5xSrwo2jt7mCy8sj+yOJe9aC5la0vVSdrkVA=="

# AWS_STORAGE_BUCKET_NAME = "cc-a1"
